Query:
  type: object
  config:
    fields:
      cards:
        description: Get all cards.
        type: 'CardsPage'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Card\\CardsResolver", [args])'
        args:
          page:
            type: Int
            defaultValue: 1
          pageSize:
            type: Int
            defaultValue: 30
          name:
            type: String
          colors:
            type: String
          types:
            type: String
          subtypes:
            type: String
      card:
        description: Get a specific card.
        type: Card
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Card\\CardResolver", [args])'
        args:
          multiverseId:
            type: Int
          set:
            type: String
          number:
            type: String
          name:
            type: String